### ISSUE TITLE
コーディングスタイルの規約の決定

### ISSUE THREAD

**Issue by yassu** [ggjsap-2016-t3/before_jam#4]
このissueではコーディング規約を決定することを提案します.

**Comment by tanitta** [comment]
軽めの規約をとりあえずの叩き台で書いたのでコミットしておきますね．

**Comment by yassu** [comment]
内容については、良いと思います (というか、何も言うことができません).
ですが, styleguideのmarkdown自体のstyleがよろしくないように思います.
具体的には,
- `#`の後に空白が挿入されていない
- sectionの間に空行が挿入されていない (区切られていない).
- 具体例としての意味と, 内容としての意味のどちらも持っている内容があるため, 分かりづらいように感じる.

これらは修正した方がいいと思います (自分が修正して良いでしょうか?).

**Comment by tanitta** [comment]
修正していただけると嬉しいです！

**Comment by yassu** [comment]
変更しました: コミットは[ここ](https://github.com/ggjsap-2016-t3/before_jam/commit/b8f6e910bb2574bb8edbb43780cd3c5fc9358b3f)

**Comment by tanitta** [comment]
ありがとうございます，例が増えて分かりやすくなりましたね．一旦マージしましょうか？

**Comment by yassu** [comment]
Slackの方でも書きましたが,
今のところ自分とtanittaさんしかコメントしていないので, 後最低一人のレビューを受けてからマージした方が良いと思います. どうでしょうか?

**Comment by mktakuya** [comment]
良いと思います！ :+1:
privateのメソッド名に_つけるの忘れてしまいそうですが……

**Comment by yassu** [comment]
mergeしました.
